import type {
  GearSlot,
  Habitat,
  Item,
  MorphColors,
  RankInfo,
  Rarity,
  Rival,
  Species,
  Stats,
} from "./types.ts";
import { SEASON2_HABITATS, SEASON2_ITEMS, SEASON2_RIVALS, SEASON2_SPECIES } from "./packs/season2.ts";
import { SEASON3_HABITATS, SEASON3_ITEMS, SEASON3_RIVALS, SEASON3_SPECIES } from "./packs/season3.ts";
import { SEASON4_HABITATS, SEASON4_ITEMS, SEASON4_RIVALS, SEASON4_SPECIES } from "./packs/season4.ts";
import { SEASON5_HABITATS, SEASON5_ITEMS, SEASON5_RIVALS, SEASON5_SPECIES } from "./packs/season5.ts";

export const SAVE_VERSION = 13;
export const MAX_STAT = 42;
export const TEAM_SIZE = 3;
export const HUNTS_PER_DAY = 6;

export const ZERO_STATS: Stats = {
  power: 0,
  speed: 0,
  grit: 0,
  venom: 0,
  silk: 0,
  size: 0,
};

const hentzF: MorphColors = {
  abdomen: "#9a6844",
  abdomenLight: "#c9a06c",
  folium: "#3a2418",
  speckle: "#e2d3b4",
  cephalothorax: "#4a3326",
  legDark: "#4a3224",
  legLight: "#d7c6a6",
  fang: "#2a1c14",
};

const hentzM: MorphColors = {
  abdomen: "#c45c32",
  abdomenLight: "#e07848",
  folium: "#6b2a18",
  speckle: "#f0c9a0",
  cephalothorax: "#5a3020",
  legDark: "#4a2a1c",
  legLight: "#d9c4a4",
  fang: "#2a1410",
};

export const SPECIES: Record<string, Species> = {
  hentz: {
    id: "hentz",
    common: "Hentz Orbweaver",
    latin: "Neoscona crucifera",
    rarity: "common",
    blurb:
      "The porch spider of the South. Heavy abdomen, banded legs, mean on a stick. Your first fighter.",
    portraits: {
      female: "/images/spiders/hentz-f.jpg",
      male: "/images/spiders/hentz-m.jpg",
    },
    hanging: "/images/spiders/hang-rust.jpg",
    colors: hentzF,
    maleColors: hentzM,
    bases: { power: 7, speed: 6, grit: 7, venom: 4, silk: 6, size: 7 },
    spread: { power: 3, speed: 3, grit: 3, venom: 2, silk: 2, size: 3 },
    traits: ["Porch-bred", "Night feeder", "Stubborn"],
    habitats: ["porch", "garden", "barn", "woods"],
    web: { name: "Porch snare", style: "orb", move: "lunge", ability: "Lunge hits harder" },
  },
  cross: {
    id: "cross",
    common: "Cross Orbweaver",
    latin: "Araneus diadematus",
    rarity: "uncommon",
    blurb: "White cross on a plump back. Tanks a beating and gives one back.",
    portraits: { default: "/images/spiders/cross.jpg" },
    colors: {
      abdomen: "#b06a38",
      abdomenLight: "#d4a06a",
      folium: "#5a3018",
      speckle: "#f0ead8",
      cephalothorax: "#4a3020",
      legDark: "#3a281c",
      legLight: "#cbb892",
      fang: "#241810",
    },
    bases: { power: 8, speed: 5, grit: 9, venom: 4, silk: 5, size: 8 },
    spread: { power: 3, speed: 2, grit: 3, venom: 2, silk: 2, size: 2 },
    traits: ["Garden cross", "Heavy", "Patient"],
    habitats: ["garden", "barn", "woods"],
    web: { name: "Cross brace", style: "cross", move: "brace", ability: "Brace restores extra stamina" },
  },
  shamrock: {
    id: "shamrock",
    common: "Shamrock Orbweaver",
    latin: "Araneus trifolium",
    rarity: "uncommon",
    blurb: "Clover-marked and thick as a pecan. Hits like a dropped brick.",
    portraits: { default: "/images/spiders/shamrock.jpg" },
    colors: {
      abdomen: "#c47838",
      abdomenLight: "#e8b06a",
      folium: "#8a4020",
      speckle: "#f2d8a8",
      cephalothorax: "#6a3820",
      legDark: "#5a3020",
      legLight: "#e0c8a0",
      fang: "#2a1810",
    },
    bases: { power: 9, speed: 4, grit: 8, venom: 3, silk: 5, size: 9 },
    spread: { power: 3, speed: 2, grit: 3, venom: 2, silk: 2, size: 3 },
    traits: ["Clover back", "Slow", "Crushing"],
    habitats: ["garden", "woods", "fair"],
    web: { name: "Pecan lattice", style: "spoked", move: "grapple", ability: "Grapple hits harder" },
  },
  catface: {
    id: "catface",
    common: "Cat-faced Orbweaver",
    latin: "Araneus gemmoides",
    rarity: "uncommon",
    blurb: "Two dark peaks like ears. Gritty, ugly, and hard to put down.",
    portraits: { default: "/images/spiders/catface.jpg" },
    colors: {
      abdomen: "#c4a078",
      abdomenLight: "#e8d0a8",
      folium: "#5a4030",
      speckle: "#f4ead0",
      cephalothorax: "#6a5040",
      legDark: "#4a3828",
      legLight: "#dcc8a8",
      fang: "#2a2018",
    },
    bases: { power: 6, speed: 6, grit: 10, venom: 4, silk: 6, size: 8 },
    spread: { power: 2, speed: 3, grit: 3, venom: 2, silk: 2, size: 2 },
    traits: ["Cat-faced", "Iron gut", "Watchful"],
    habitats: ["barn", "porch", "woods"],
    web: { name: "Eave tangle", style: "tangle", move: "brace", ability: "Brace restores extra stamina" },
  },
  marbled: {
    id: "marbled",
    common: "Marbled Orbweaver",
    latin: "Araneus marmoreus",
    rarity: "rare",
    blurb: "Pumpkin marble. Looks like jewelry until it locks on.",
    portraits: { default: "/images/spiders/marbled.jpg" },
    colors: {
      abdomen: "#e09028",
      abdomenLight: "#f4c860",
      folium: "#5a2810",
      speckle: "#f8e8b0",
      cephalothorax: "#8a4820",
      legDark: "#6a3018",
      legLight: "#f0c878",
      fang: "#301808",
    },
    bases: { power: 8, speed: 7, grit: 6, venom: 6, silk: 7, size: 7 },
    spread: { power: 3, speed: 3, grit: 2, venom: 3, silk: 3, size: 2 },
    traits: ["Marbled", "Showy", "Hot-blooded"],
    habitats: ["woods", "garden", "fair"],
    web: { name: "Marble spiral", style: "spoked", move: "feint", ability: "Feint hits harder" },
  },
  arrowhead: {
    id: "arrowhead",
    common: "Arrowhead Orbweaver",
    latin: "Verrucosa arenata",
    rarity: "rare",
    blurb: "Triangle abdomen, a living arrow. Venom first, questions later.",
    portraits: { default: "/images/spiders/arrowhead.jpg" },
    colors: {
      abdomen: "#f0ece4",
      abdomenLight: "#ffffff",
      folium: "#8a6a50",
      speckle: "#d4c4b0",
      cephalothorax: "#b05038",
      legDark: "#6a3020",
      legLight: "#e8d0c0",
      fang: "#401810",
    },
    bases: { power: 6, speed: 8, grit: 5, venom: 10, silk: 6, size: 5 },
    spread: { power: 2, speed: 3, grit: 2, venom: 3, silk: 2, size: 2 },
    traits: ["Arrowback", "Quick fang", "Skittish"],
    habitats: ["woods", "garden"],
    web: { name: "Arrow line", style: "tangle", move: "lunge", ability: "Lunge hits harder" },
  },
  spiny: {
    id: "spiny",
    common: "Spinybacked Orbweaver",
    latin: "Gasteracantha cancriformis",
    rarity: "rare",
    blurb: "Crab-shaped with red spines. Armor you can see.",
    portraits: { default: "/images/spiders/spiny.jpg" },
    colors: {
      abdomen: "#f4f0e8",
      abdomenLight: "#ffffff",
      folium: "#c03028",
      speckle: "#e04030",
      cephalothorax: "#2a2018",
      legDark: "#1a1410",
      legLight: "#8a7a68",
      fang: "#100c08",
    },
    bases: { power: 5, speed: 5, grit: 12, venom: 5, silk: 4, size: 4 },
    spread: { power: 2, speed: 2, grit: 3, venom: 2, silk: 2, size: 1 },
    traits: ["Spined", "Armored", "Crab-stance"],
    habitats: ["garden", "fair", "woods"],
    web: { name: "Spine net", style: "cross", move: "brace", ability: "Brace restores extra stamina" },
  },
  golden: {
    id: "golden",
    common: "Golden Silk Orbweaver",
    latin: "Trichonephila clavipes",
    rarity: "legendary",
    blurb: "Long gold legs, silk that sings. Yank specialists.",
    portraits: { default: "/images/spiders/golden.jpg" },
    colors: {
      abdomen: "#c8a028",
      abdomenLight: "#f0d060",
      folium: "#3a3010",
      speckle: "#f8e890",
      cephalothorax: "#8a6820",
      legDark: "#2a2010",
      legLight: "#e8c040",
      fang: "#201808",
    },
    bases: { power: 7, speed: 8, grit: 6, venom: 5, silk: 12, size: 8 },
    spread: { power: 2, speed: 3, grit: 2, venom: 2, silk: 3, size: 2 },
    traits: ["Golden wind", "Long-leg", "Silk singer"],
    habitats: ["woods", "fair"],
    web: { name: "Golden dragline", style: "golden", move: "yank", ability: "Yank pulls farther" },
  },
  joro: {
    id: "joro",
    common: "Joro Silk",
    latin: "Trichonephila clavata",
    rarity: "legendary",
    blurb: "Yellow-black immigrant queen. Fast, venomous, and expensive to lose.",
    portraits: { default: "/images/spiders/joro.jpg" },
    colors: {
      abdomen: "#e8d020",
      abdomenLight: "#f8f070",
      folium: "#1a3a38",
      speckle: "#c02828",
      cephalothorax: "#2a2820",
      legDark: "#1a1814",
      legLight: "#e8c030",
      fang: "#10100c",
    },
    bases: { power: 9, speed: 9, grit: 7, venom: 8, silk: 9, size: 7 },
    spread: { power: 3, speed: 3, grit: 2, venom: 3, silk: 3, size: 2 },
    traits: ["Joro", "Invasive", "Showboat"],
    habitats: ["fair", "woods", "garden"],
    web: { name: "Joro bridge", style: "golden", move: "drop", ability: "Drop pays out less silk" },
  },
  widow: {
    id: "widow",
    common: "Southern Black Widow",
    latin: "Latrodectus mactans",
    rarity: "legendary",
    blurb: "Hourglass on a black gut. Venom first. Boss of the stick.",
    portraits: { default: "/images/spiders/hentz-f.jpg" },
    colors: {
      abdomen: "#0c0c0c",
      abdomenLight: "#1c1c1c",
      folium: "#e02020",
      speckle: "#e02020",
      cephalothorax: "#0a0a0a",
      legDark: "#050505",
      legLight: "#2a2a2a",
      fang: "#8a1010",
    },
    bases: { power: 9, speed: 8, grit: 10, venom: 14, silk: 8, size: 6 },
    spread: { power: 2, speed: 2, grit: 2, venom: 2, silk: 2, size: 1 },
    traits: ["Hourglass", "Venom queen", "Doesn't blink"],
    habitats: [],
    web: { name: "Widow's thread", style: "tangle", move: "lunge", ability: "Lunge hits harder" },
  },
};

Object.assign(SPECIES, SEASON2_SPECIES, SEASON3_SPECIES, SEASON4_SPECIES, SEASON5_SPECIES);

export const SPECIES_LIST = Object.values(SPECIES);

export const RANKS: RankInfo[] = [
  { id: 0, name: "Alley", blurb: "Stick fights behind the dumpster.", points: 0, purse: 18 },
  { id: 1, name: "Backyard", blurb: "Kids on the fence, cash in a coffee can.", points: 40, purse: 32 },
  { id: 2, name: "District", blurb: "Porch lights and side bets.", points: 110, purse: 55 },
  { id: 3, name: "County Fair", blurb: "Red clay, string lights, a real purse.", points: 220, purse: 90 },
  { id: 4, name: "State Circuit", blurb: "Travel case, motel ice, mean spiders.", points: 380, purse: 140 },
  { id: 5, name: "Regional", blurb: "Named stables. They scout you now.", points: 580, purse: 210 },
  { id: 6, name: "National Silk", blurb: "The stick circuit that makes papers.", points: 840, purse: 320 },
  { id: 7, name: "World Stick", blurb: "Hold the stick. Don't drop the legend.", points: 1180, purse: 480 },
];

export const HABITATS: Habitat[] = [
  {
    id: "porch",
    name: "Night Porch",
    blurb: "Bug light, moths, and a web in the eave.",
    image: "/images/bg/porch.jpg",
    rank: 0,
    cost: 0,
    energy: 12,
    weights: { common: 70, uncommon: 24, rare: 6 },
    species: ["hentz", "catface", "cross"],
    night: true,
  },
  {
    id: "garden",
    name: "Garden Fence",
    blurb: "Azaleas, pine straw, gold light in the orbs.",
    image: "/images/bg/garden.jpg",
    rank: 1,
    cost: 8,
    energy: 14,
    weights: { common: 50, uncommon: 35, rare: 13, legendary: 2 },
    species: ["hentz", "cross", "shamrock", "arrowhead", "spiny"],
  },
  {
    id: "barn",
    name: "Dust Barn",
    blurb: "Hay, plank light, rafters full of silk.",
    image: "/images/bg/barn.jpg",
    rank: 2,
    cost: 14,
    energy: 16,
    weights: { common: 40, uncommon: 40, rare: 16, legendary: 4 },
    species: ["hentz", "catface", "cross", "shamrock"],
  },
  {
    id: "woods",
    name: "Kudzu Line",
    blurb: "Pine edge, chain-link, webs between saplings.",
    image: "/images/bg/woods.jpg",
    rank: 3,
    cost: 22,
    energy: 18,
    weights: { common: 25, uncommon: 40, rare: 26, legendary: 9 },
    species: ["marbled", "arrowhead", "golden", "joro", "shamrock", "hentz"],
  },
  {
    id: "fair",
    name: "Fairgrounds",
    blurb: "After the crowd leaves, the big ones come in.",
    image: "/images/bg/fair.jpg",
    rank: 4,
    cost: 36,
    energy: 20,
    weights: { uncommon: 30, rare: 45, legendary: 25 },
    species: ["joro", "golden", "spiny", "marbled", "shamrock"],
  },
];

HABITATS.push(...SEASON2_HABITATS, ...SEASON3_HABITATS, ...SEASON4_HABITATS, ...SEASON5_HABITATS);

export const ITEMS: Record<string, Item> = {
  "porch-twine": {
    id: "porch-twine",
    name: "Porch Twine",
    kind: "wraps",
    slot: "wraps",
    price: 14,
    blurb: "Kitchen string wrapped at the joints. Better than nothing.",
    bonus: { grit: 1 },
    rank: 0,
  },
  "leather-wraps": {
    id: "leather-wraps",
    name: "Leather Wraps",
    kind: "wraps",
    slot: "wraps",
    price: 48,
    blurb: "Boot-leather strips. Holds a hit.",
    bonus: { grit: 3, size: 1 },
    rank: 1,
  },
  "chitin-plates": {
    id: "chitin-plates",
    name: "Chitin Plates",
    kind: "wraps",
    slot: "wraps",
    price: 130,
    blurb: "Shed plates wired on. Heavy armor.",
    bonus: { grit: 6, speed: -1 },
    rank: 3,
  },
  "silk-mail": {
    id: "silk-mail",
    name: "Silk Mail",
    kind: "wraps",
    slot: "wraps",
    price: 290,
    blurb: "Woven dragline over the abdomen. Champion kit.",
    bonus: { grit: 8, silk: 2 },
    rank: 5,
  },
  "dew-oil": {
    id: "dew-oil",
    name: "Dew Oil",
    kind: "fang",
    slot: "fang",
    price: 18,
    blurb: "Morning dew and crushed mite. A little sting.",
    bonus: { venom: 2 },
    rank: 0,
  },
  "mite-oil": {
    id: "mite-oil",
    name: "Mite Oil",
    kind: "fang",
    slot: "fang",
    price: 58,
    blurb: "Rendered mite fat. Fangs drink it.",
    bonus: { venom: 4 },
    rank: 2,
  },
  "widow-whisper": {
    id: "widow-whisper",
    name: "Widow Whisper",
    kind: "fang",
    slot: "fang",
    price: 170,
    blurb: "Don't ask where it came from.",
    bonus: { venom: 7 },
    rank: 4,
  },
  "black-drop": {
    id: "black-drop",
    name: "Black Drop",
    kind: "fang",
    slot: "fang",
    price: 360,
    blurb: "One drop. Burns the silk. Burns you if you lose it.",
    bonus: { venom: 10, grit: -1 },
    rank: 6,
  },
  "garden-thread": {
    id: "garden-thread",
    name: "Garden Thread",
    kind: "silk",
    slot: "silk",
    price: 16,
    blurb: "Collected off the tomato cages.",
    bonus: { silk: 2 },
    rank: 0,
  },
  "dragline-resin": {
    id: "dragline-resin",
    name: "Dragline Resin",
    kind: "silk",
    slot: "silk",
    price: 74,
    blurb: "Sticky, loud, and hard to cut.",
    bonus: { silk: 5, speed: 1 },
    rank: 2,
  },
  "golden-wind": {
    id: "golden-wind",
    name: "Golden Wind",
    kind: "silk",
    slot: "silk",
    price: 240,
    blurb: "Trichonephila silk. Sings when it pulls.",
    bonus: { silk: 9 },
    rank: 5,
  },
  "cricket-mash": {
    id: "cricket-mash",
    name: "Cricket Mash",
    kind: "stim",
    slot: "stim",
    price: 24,
    blurb: "A jolt. Burns off after a few bouts.",
    bonus: { speed: 3 },
    stimFights: 4,
    rank: 0,
  },
  "red-clay": {
    id: "red-clay",
    name: "Red Clay Dust",
    kind: "stim",
    slot: "stim",
    price: 86,
    blurb: "Fairground dirt on the palps. Meaner, quicker.",
    bonus: { speed: 5, power: 1 },
    stimFights: 3,
    rank: 3,
  },
  "night-moth": {
    id: "night-moth",
    name: "Night Moth",
    kind: "stim",
    slot: "stim",
    price: 190,
    blurb: "Eaten live. Two fights of lightning.",
    bonus: { speed: 8 },
    stimFights: 2,
    rank: 5,
  },
  "acorn-cap": {
    id: "acorn-cap",
    name: "Acorn Cap",
    kind: "charm",
    slot: "charm",
    price: 26,
    blurb: "Kid luck. Sometimes it works.",
    bonus: { luck: 2 },
    rank: 0,
  },
  "lucky-pecan": {
    id: "lucky-pecan",
    name: "Lucky Pecan",
    kind: "charm",
    slot: "charm",
    price: 96,
    blurb: "Carried in a matchbox since '04.",
    bonus: { luck: 5 },
    rank: 2,
  },
  "fair-ribbon": {
    id: "fair-ribbon",
    name: "Fair Ribbon",
    kind: "charm",
    slot: "charm",
    price: 210,
    blurb: "Blue once. Faded now. Still pulls purses.",
    bonus: { luck: 8 },
    rank: 4,
  },
  "widow-knot": {
    id: "widow-knot",
    name: "Widow Knot",
    kind: "charm",
    slot: "charm",
    price: 0,
    blurb: "A hard black knot cut from the far silk. First Widow win only.",
    bonus: { venom: 3, luck: 5 },
    rewardOnly: true,
    rank: 0,
  },
  "tom-tab": {
    id: "tom-tab",
    name: "Trash Can Tab",
    kind: "charm",
    slot: "charm",
    price: 0,
    blurb: "Alley Tom's bent tab. First win only. A little luck under the shell.",
    bonus: { luck: 1, power: 1 },
    rewardOnly: true,
    rank: 0,
  },
  "kudzu-cord": {
    id: "kudzu-cord",
    name: "Kudzu Cord",
    kind: "wraps",
    slot: "wraps",
    price: 0,
    blurb: "A green cord cut from the ditch line. First Kudzu Kids win only.",
    bonus: { grit: 2, silk: 1 },
    rewardOnly: true,
    rank: 0,
  },
  "clay-ribbon": {
    id: "clay-ribbon",
    name: "Red Clay Ribbon",
    kind: "charm",
    slot: "charm",
    price: 0,
    blurb: "A ribbon taken after the fairground call. First Red Clay Stable win only.",
    bonus: { luck: 3, venom: 1 },
    rewardOnly: true,
    rank: 0,
  },
  "state-pass": {
    id: "state-pass",
    name: "State Pass",
    kind: "silk",
    slot: "silk",
    price: 0,
    blurb: "Stamped silk from a road crew's travel case. First State Circuit win only.",
    bonus: { speed: 2, silk: 3 },
    rewardOnly: true,
    rank: 0,
  },
  "silk-key": {
    id: "silk-key",
    name: "Silk National Key",
    kind: "fang",
    slot: "fang",
    price: 0,
    blurb: "A service-gate key filed to a point. First Gate Seven win only.",
    bonus: { venom: 2, grit: 3 },
    rewardOnly: true,
    rank: 0,
    season: 4,
  },
  "world-seal": {
    id: "world-seal",
    name: "World Stick Seal",
    kind: "charm",
    slot: "charm",
    price: 0,
    blurb: "A wax seal from the last call. First Stick World win only.",
    bonus: { power: 3, luck: 5 },
    rewardOnly: true,
    rank: 0,
  },
  cricket: {
    id: "cricket",
    name: "Field Cricket",
    kind: "feed",
    price: 6,
    blurb: "Staple feed. Fills the tank.",
    rank: 0,
  },
  moth: {
    id: "moth",
    name: "Porch Moth",
    kind: "feed",
    price: 11,
    blurb: "Fatty. Helps them swell toward a molt.",
    rank: 0,
  },
  hopper: {
    id: "hopper",
    name: "Grasshopper",
    kind: "feed",
    price: 18,
    blurb: "A real meal. Energy and size.",
    rank: 1,
  },
  wasp: {
    id: "wasp",
    name: "Paper Wasp",
    kind: "feed",
    price: 24,
    blurb: "Dangerous to catch, hotter in the fangs.",
    rank: 2,
  },
  "sugar-water": {
    id: "sugar-water",
    name: "Sugar Water",
    kind: "bait",
    price: 15,
    blurb: "Next hunt leans uncommon.",
    rank: 0,
  },
  "porch-bulb": {
    id: "porch-bulb",
    name: "Spare Bulb",
    kind: "bait",
    price: 22,
    blurb: "Brighter light. Night porch runs hotter.",
    rank: 1,
  },
  pheromone: {
    id: "pheromone",
    name: "Silk Pheromone",
    kind: "bait",
    price: 64,
    blurb: "Next hunt can pull a legend.",
    rank: 3,
  },
  "field-salve": {
    id: "field-salve",
    name: "Field Salve",
    kind: "tonic",
    price: 36,
    blurb: "Clears an injury. They'll fight tomorrow.",
    rank: 0,
  },
  "morale-tea": {
    id: "morale-tea",
    name: "Morale Tea",
    kind: "tonic",
    price: 14,
    blurb: "Mashed mint and sugar. Settles a rattled fighter.",
    rank: 0,
  },
  "molt-tonic": {
    id: "molt-tonic",
    name: "Molt Tonic",
    kind: "tonic",
    price: 95,
    blurb: "Pushes a near-ready spider over the edge.",
    rank: 2,
  },
  "extra-crate": {
    id: "extra-crate",
    name: "Extra Crate",
    kind: "upgrade",
    price: 160,
    blurb: "Two more berths in the stable.",
    rank: 1,
  },
  "travel-case": {
    id: "travel-case",
    name: "Travel Case",
    kind: "upgrade",
    price: 420,
    blurb: "Circuit kit. Two more berths.",
    rank: 4,
  },
};

Object.assign(ITEMS, SEASON2_ITEMS, SEASON3_ITEMS, SEASON4_ITEMS, SEASON5_ITEMS);

export const ITEM_LIST = Object.values(ITEMS);

export const SLOT_LABEL: Record<GearSlot, string> = {
  wraps: "Wraps",
  fang: "Fang",
  silk: "Silk",
  stim: "Stim",
  charm: "Charm",
};

export const RIVALS: Rival[] = [
  {
    id: "widow",
    name: "Black Widow",
    rank: 1,
    quote: "Hourglass. Full stop.",
    bias: ["widow"],
    teamSize: 1,
    grit: 1.4,
    style: "lunge",
    always: true,
    mind: true,
  },
  { id: "tom", name: "Alley Tom", rank: 0, quote: "Found mine in a trash can.", bias: ["hentz"], teamSize: 1, grit: 0.7, style: "brace" },
  { id: "june", name: "June on the Fence", rank: 0, quote: "Don't blink.", bias: ["hentz", "cross"], teamSize: 1, grit: 0.85, style: "feint" },
  { id: "kudzu", name: "The Kudzu Kids", rank: 1, quote: "We run the ditch.", bias: ["hentz", "catface"], teamSize: 2, grit: 0.9, style: "grapple" },
  { id: "pecan", name: "Pecan Street", rank: 1, quote: "Cash on the barrel.", bias: ["cross", "shamrock"], teamSize: 1, grit: 1, style: "brace" },
  { id: "porchclub", name: "Night Porch Club", rank: 2, quote: "Lights out.", bias: ["catface", "hentz"], teamSize: 2, grit: 1.05, style: "yank" },
  { id: "hayloft", name: "Hayloft Five", rank: 2, quote: "Barn rules.", bias: ["shamrock", "cross"], teamSize: 2, grit: 1.1, style: "grapple" },
  { id: "clay", name: "Red Clay Stable", rank: 3, quote: "Fair's this weekend.", bias: ["marbled", "shamrock"], teamSize: 2, grit: 1.15, style: "feint" },
  { id: "ribbon", name: "Ribbon Thieves", rank: 3, quote: "We keep what we beat.", bias: ["arrowhead", "spiny"], teamSize: 3, grit: 1.2, style: "drop" },
  { id: "circuit", name: "State Circuit", rank: 4, quote: "Travel mean.", bias: ["golden", "marbled"], teamSize: 3, grit: 1.25, style: "yank" },
  { id: "moth", name: "Moth Hour", rank: 4, quote: "After the bulb dies.", bias: ["joro", "arrowhead"], teamSize: 2, grit: 1.3, style: "drop" },
  { id: "magnolia", name: "Magnolia Crew", rank: 5, quote: "Pretty yard. Ugly fights.", bias: ["golden", "joro"], teamSize: 3, grit: 1.35, style: "lunge" },
  { id: "silkmen", name: "The Silkmen", rank: 6, quote: "Don't wager what you can't molt back.", bias: ["joro", "golden", "spiny"], teamSize: 3, grit: 1.45, style: "yank" },
  { id: "world", name: "Stick World", rank: 7, quote: "Hold it.", bias: ["joro", "golden", "marbled"], teamSize: 3, grit: 1.6, style: "grapple" },
];

RIVALS.push(...SEASON2_RIVALS, ...SEASON3_RIVALS, ...SEASON4_RIVALS, ...SEASON5_RIVALS);

export const NAMES_F = [
  "Cinder", "Dixie", "Magnolia", "Junebug", "Clover", "Sable", "Moth", "Pecan",
  "Shade", "Twig", "Ember", "Hickory", "Nola", "Bramble", "Vesper", "Calico",
];
export const NAMES_M = [
  "Rusty", "Porch", "Kudzu", "Needle", "Cricket", "Biscuit", "Red", "Hick",
  "Caddo", "Stick", "Juniper", "Clay", "Weevil", "Thorn", "Ash", "Bo",
];

export const TRAIT_POOL = [
  "Mean in close",
  "Drops on a dime",
  "Night eyes",
  "Heavy abdomen",
  "Silk hoarder",
  "Fence-trained",
  "Won't quit",
  "Easy rattle",
  "Fair veteran",
  "Molt glutton",
];

export const MOVES = {
  lunge: {
    id: "lunge" as const,
    name: "Lunge",
    beats: "feint",
    loses: "grapple",
    stamina: 16,
    power: 1.15,
    tell: "Legs fan wide.",
  },
  grapple: {
    id: "grapple" as const,
    name: "Grapple",
    beats: "lunge",
    loses: "feint",
    stamina: 18,
    power: 1.05,
    tell: "Body drops on the silk.",
  },
  feint: {
    id: "feint" as const,
    name: "Feint",
    beats: "grapple",
    loses: "lunge",
    stamina: 12,
    power: 0.85,
    tell: "A twitch back, then nothing.",
  },
  brace: {
    id: "brace" as const,
    name: "Brace",
    beats: "",
    loses: "",
    stamina: 8,
    power: 0.2,
    tell: "Legs tuck in.",
  },
  yank: {
    id: "yank" as const,
    name: "Silk Yank",
    beats: "drop",
    loses: "brace",
    stamina: 14,
    power: 0.7,
    tell: "The thread pulses.",
  },
  drop: {
    id: "drop" as const,
    name: "Drop",
    beats: "lunge",
    loses: "yank",
    stamina: 10,
    power: 0.35,
    tell: "Silk pays out.",
  },
};

export const STAGE_ORDER: Array<import("./types").Stage> = [
  "nymph",
  "juvenile",
  "adult",
  "veteran",
  "champion",
  "legend",
];

export const RARITY_TINT: Record<Rarity, string> = {
  common: "text-dust",
  uncommon: "text-moss",
  rare: "text-rust",
  legendary: "text-paper",
};

export function xpToNext(level: number): number {
  return Math.round(40 + level * 28 + level * level * 4);
}

export function maxHp(size: number, grit: number, stage: string): number {
  const stageBonus =
    stage === "legend" ? 40 : stage === "champion" ? 28 : stage === "veteran" ? 18 : stage === "adult" ? 10 : 0;
  return Math.round(72 + size * 4.2 + grit * 3.4 + stageBonus);
}

export function maxEnergy(size: number): number {
  return Math.round(70 + size * 3);
}
