import type { Habitat, Item, Rival, Species } from "../types.ts";

/** Pit Circuit. Ground spiders, crawlspaces, and the mills that don't hang. */

export const SEASON7_SPECIES: Record<string, Species> = {
  recluse: {
    id: "recluse",
    common: "Brown Recluse",
    latin: "Loxosceles reclusa",
    rarity: "rare",
    blurb: "Violin on a beige back. She doesn't look like much until the bite writes its name.",
    portraits: { default: "/images/spiders/recluse.jpg" },
    colors: {
      abdomen: "#c4a878",
      abdomenLight: "#e8d4a8",
      folium: "#6a4a28",
      speckle: "#f0e0c0",
      cephalothorax: "#b89058",
      legDark: "#8a6a40",
      legLight: "#dcc8a0",
      fang: "#3a2410",
    },
    bases: { power: 5, speed: 9, grit: 6, venom: 13, silk: 5, size: 4 },
    spread: { power: 2, speed: 3, grit: 2, venom: 3, silk: 2, size: 1 },
    traits: ["Violin back", "Necrotic", "Crevice keeper"],
    habitats: ["crawlspace"],
    web: { name: "Mess sheet", style: "sheet", move: "lunge", ability: "Lunge hits harder", surge: "ambush" },
    season: 7,
    weight: "thread",
  },
  huntsman: {
    id: "huntsman",
    common: "Huntsman",
    latin: "Heteropoda venatoria",
    rarity: "uncommon",
    blurb: "Crab gait on a porch wall. She doesn't spin a snare — she runs you down.",
    portraits: { default: "/images/spiders/huntsman.jpg" },
    colors: {
      abdomen: "#b08a58",
      abdomenLight: "#d4b888",
      folium: "#5a4030",
      speckle: "#e8d4b0",
      cephalothorax: "#8a6848",
      legDark: "#4a3828",
      legLight: "#c4a078",
      fang: "#2a1c10",
    },
    bases: { power: 8, speed: 12, grit: 7, venom: 6, silk: 4, size: 8 },
    spread: { power: 2, speed: 3, grit: 2, venom: 2, silk: 1, size: 2 },
    traits: ["Wall runner", "Crab gait", "Night eyes"],
    habitats: ["crawlspace", "porch"],
    web: { name: "Wall dash", style: "orb", move: "feint", ability: "Feint hits harder", surge: "reel" },
    season: 7,
    weight: "floor",
  },
  trapdoor: {
    id: "trapdoor",
    common: "Trapdoor Spider",
    latin: "Ummidia audouini",
    rarity: "rare",
    blurb: "Waits under a silk-hinged lid. When it opens, the fight is already over.",
    portraits: { default: "/images/spiders/trapdoor.jpg" },
    colors: {
      abdomen: "#3a281c",
      abdomenLight: "#6a4a32",
      folium: "#1a120c",
      speckle: "#a08060",
      cephalothorax: "#2a1c14",
      legDark: "#18100c",
      legLight: "#6a5038",
      fang: "#100c08",
    },
    bases: { power: 9, speed: 5, grit: 12, venom: 7, silk: 4, size: 10 },
    spread: { power: 3, speed: 2, grit: 3, venom: 2, silk: 1, size: 2 },
    traits: ["Burrow lid", "Ambush wait", "Iron gut"],
    habitats: ["claybank"],
    web: { name: "Lid ambush", style: "tangle", move: "brace", ability: "Brace restores extra stamina", surge: "ambush" },
    season: 7,
    weight: "floor",
  },
  tarantula: {
    id: "tarantula",
    common: "Texas Brown Tarantula",
    latin: "Aphonopelma hentzi",
    rarity: "rare",
    blurb: "A walking fist of rust hair. She doesn't hang the stick — she owns the pit.",
    portraits: { default: "/images/spiders/tarantula.jpg" },
    colors: {
      abdomen: "#8a4a28",
      abdomenLight: "#c47848",
      folium: "#3a2010",
      speckle: "#e0a878",
      cephalothorax: "#5a3020",
      legDark: "#2a1810",
      legLight: "#a06840",
      fang: "#1a1008",
    },
    bases: { power: 11, speed: 4, grit: 11, venom: 6, silk: 3, size: 12 },
    spread: { power: 3, speed: 2, grit: 3, venom: 2, silk: 1, size: 2 },
    traits: ["Urticating", "Pit-bred", "Crushing"],
    habitats: ["claybank"],
    web: { name: "Pit shove", style: "cross", move: "grapple", ability: "Grapple hits harder", surge: "harden" },
    season: 7,
    weight: "pit",
  },
  birdeater: {
    id: "birdeater",
    common: "Goliath Bird-eater",
    latin: "Theraphosa blondi",
    rarity: "legendary",
    blurb: "The biggest mill on the circuit. Dinner-plate legs. The stick looks like a twig.",
    portraits: { default: "/images/spiders/birdeater.jpg" },
    colors: {
      abdomen: "#7a3a18",
      abdomenLight: "#c06028",
      folium: "#2a1408",
      speckle: "#e09040",
      cephalothorax: "#4a2410",
      legDark: "#1a0c08",
      legLight: "#8a4820",
      fang: "#140804",
    },
    bases: { power: 12, speed: 4, grit: 10, venom: 7, silk: 2, size: 14 },
    spread: { power: 3, speed: 1, grit: 2, venom: 2, silk: 1, size: 2 },
    traits: ["Bird-eater", "Urticating", "Heavy"],
    habitats: ["claybank"],
    web: { name: "Goliath lock", style: "cross", move: "grapple", ability: "Grapple hits harder", surge: "harden" },
    season: 7,
    weight: "pit",
  },
};

export const SEASON7_HABITATS: Habitat[] = [
  {
    id: "crawlspace",
    name: "Crawlspace",
    blurb: "Dirt, brick piers, and a violin in the dark.",
    image: "/images/bg/crawlspace.jpg",
    rank: 3,
    cost: 28,
    energy: 18,
    weights: { uncommon: 38, rare: 48, legendary: 14 },
    species: ["recluse", "huntsman", "brownwidow", "jumper"],
    night: true,
    season: 7,
  },
  {
    id: "claybank",
    name: "Red Clay Bank",
    blurb: "Burrow lids in the cutbank. The pit starts here.",
    image: "/images/bg/claybank.jpg",
    rank: 5,
    cost: 54,
    energy: 22,
    weights: { uncommon: 22, rare: 48, legendary: 30 },
    species: ["tarantula", "trapdoor", "birdeater", "wolf"],
    season: 7,
  },
];

export const SEASON7_ITEMS: Record<string, Item> = {
  "recluse-drop": {
    id: "recluse-drop",
    name: "Recluse Drop",
    kind: "fang",
    slot: "fang",
    price: 220,
    blurb: "One drop. The mark stays.",
    bonus: { venom: 8, grit: -1 },
    rank: 3,
    season: 7,
  },
  "trapdoor-lid": {
    id: "trapdoor-lid",
    name: "Trapdoor Lid",
    kind: "wraps",
    slot: "wraps",
    price: 260,
    blurb: "Silk-hinged clay wired over the abdomen.",
    bonus: { grit: 7, speed: -1 },
    rank: 5,
    season: 7,
  },
  "urticating-dust": {
    id: "urticating-dust",
    name: "Urticating Dust",
    kind: "stim",
    slot: "stim",
    price: 180,
    blurb: "Kicked off a tarantula's abdomen. Two fights of mean.",
    bonus: { power: 4, grit: 2 },
    stimFights: 2,
    rank: 5,
    season: 7,
  },
  "clay-fang": {
    id: "clay-fang",
    name: "Clay Fang",
    kind: "fang",
    slot: "fang",
    price: 0,
    blurb: "A chelicera pulled from the pit. First Pit Hands win only.",
    bonus: { power: 3, venom: 2 },
    rewardOnly: true,
    rank: 0,
    season: 7,
  },
};

export const SEASON7_RIVALS: Rival[] = [
  {
    id: "saints",
    name: "Crawlspace Saints",
    rank: 3,
    quote: "You don't see the violin till it writes.",
    bias: ["recluse", "huntsman", "brownwidow"],
    teamSize: 2,
    grit: 1.22,
    style: "lunge",
    season: 7,
  },
  {
    id: "pithands",
    name: "Pit Hands",
    rank: 5,
    quote: "We don't hang 'em. We drop 'em in the hole.",
    bias: ["tarantula", "trapdoor", "birdeater"],
    teamSize: 3,
    grit: 1.5,
    style: "grapple",
    season: 7,
  },
];
