import type { Habitat, Item, Rival, Species } from "../types.ts";

/** Night Circuit pack. Live when SHIPPED_SEASON >= 2. */

export const SEASON2_SPECIES: Record<string, Species> = {
  brownwidow: {
    id: "brownwidow",
    common: "Brown Widow",
    latin: "Latrodectus geometricus",
    rarity: "rare",
    blurb: "Geometric spots, meaner than she looks. Culvert royalty.",
    portraits: { default: "/images/spiders/hentz-f.jpg" },
    colors: {
      abdomen: "#6a4a32",
      abdomenLight: "#a08058",
      folium: "#c45c28",
      speckle: "#e8d0a0",
      cephalothorax: "#4a3020",
      legDark: "#2a1c14",
      legLight: "#c4a078",
      fang: "#3a1810",
    },
    bases: { power: 7, speed: 7, grit: 8, venom: 11, silk: 7, size: 5 },
    spread: { power: 2, speed: 2, grit: 2, venom: 3, silk: 2, size: 1 },
    traits: ["Geometric", "Culvert-bred", "Hot fang"],
    habitats: ["creek", "attic"],
    web: { name: "Culvert snare", style: "tangle", move: "grapple", ability: "Grapple hits harder" },
    season: 2,
  },
  wolf: {
    id: "wolf",
    common: "Ditch Wolf",
    latin: "Tigrosa helluo",
    rarity: "rare",
    blurb: "Doesn't hang. Hunts. On a stick she still bites first.",
    portraits: { default: "/images/spiders/catface.jpg" },
    colors: {
      abdomen: "#5a4030",
      abdomenLight: "#8a6850",
      folium: "#2a2018",
      speckle: "#d4c4a8",
      cephalothorax: "#3a2a20",
      legDark: "#241810",
      legLight: "#a08060",
      fang: "#1a100c",
    },
    bases: { power: 11, speed: 9, grit: 8, venom: 6, silk: 3, size: 8 },
    spread: { power: 3, speed: 3, grit: 2, venom: 2, silk: 1, size: 2 },
    traits: ["Ground hunter", "Night eyes", "No web manners"],
    habitats: ["creek", "woods"],
    web: { name: "Ditch line", style: "tangle", move: "lunge", ability: "Lunge hits harder" },
    season: 2,
  },
  jumper: {
    id: "jumper",
    common: "Bold Jumper",
    latin: "Phidippus audax",
    rarity: "uncommon",
    blurb: "Tiny, iridescent, and she jumps the stick instead of hanging it.",
    portraits: { default: "/images/spiders/spiny.jpg" },
    colors: {
      abdomen: "#1a1a1a",
      abdomenLight: "#3a3a48",
      folium: "#c8d0e0",
      speckle: "#4a88d0",
      cephalothorax: "#1c1c24",
      legDark: "#101018",
      legLight: "#8a90a8",
      fang: "#2a2030",
    },
    bases: { power: 6, speed: 14, grit: 5, venom: 7, silk: 5, size: 3 },
    spread: { power: 2, speed: 3, grit: 2, venom: 2, silk: 2, size: 1 },
    traits: ["Jumps the line", "Peacock", "Close-range"],
    habitats: ["attic", "porch", "garden"],
    web: { name: "Sash jump", style: "orb", move: "feint", ability: "Feint hits harder" },
    season: 2,
  },
};

export const SEASON2_HABITATS: Habitat[] = [
  {
    id: "creek",
    name: "Creek Culvert",
    blurb: "Concrete mouth, slow water, silk in the rebar.",
    image: "/images/bg/woods.jpg",
    rank: 2,
    cost: 18,
    energy: 16,
    weights: { uncommon: 40, rare: 45, legendary: 15 },
    species: ["brownwidow", "wolf", "hentz", "catface"],
    season: 2,
  },
  {
    id: "attic",
    name: "Attic Window",
    blurb: "Heat, dust, a cracked pane, jumpers on the sash.",
    image: "/images/bg/barn.jpg",
    rank: 3,
    cost: 20,
    energy: 17,
    weights: { common: 20, uncommon: 40, rare: 32, legendary: 8 },
    species: ["jumper", "brownwidow", "hentz", "spiny"],
    season: 2,
  },
];

export const SEASON2_ITEMS: Record<string, Item> = {
  "culvert-silk": {
    id: "culvert-silk",
    name: "Culvert Silk",
    kind: "silk",
    slot: "silk",
    price: 88,
    blurb: "Damp, gray, and louder than porch thread.",
    bonus: { silk: 6, grit: 1 },
    rank: 2,
    season: 2,
  },
  "wolf-bristle": {
    id: "wolf-bristle",
    name: "Wolf Bristle",
    kind: "wraps",
    slot: "wraps",
    price: 110,
    blurb: "Ground-hunter hair wired at the joints.",
    bonus: { power: 4, speed: 1 },
    rank: 2,
    season: 2,
  },
  "jumper-dust": {
    id: "jumper-dust",
    name: "Jumper Dust",
    kind: "stim",
    slot: "stim",
    price: 72,
    blurb: "Iridescent scales. One bout of pure jump.",
    bonus: { speed: 7 },
    stimFights: 2,
    rank: 2,
    season: 2,
  },
};

export const SEASON2_RIVALS: Rival[] = [
  {
    id: "culvert",
    name: "Culvert Crew",
    rank: 2,
    quote: "We fight under the road.",
    bias: ["brownwidow", "wolf"],
    teamSize: 2,
    grit: 1.15,
    style: "grapple",
    season: 2,
  },
  {
    id: "ditchwolf",
    name: "Ditch Wolves",
    rank: 3,
    quote: "No silk. Just teeth.",
    bias: ["wolf", "jumper"],
    teamSize: 2,
    grit: 1.22,
    style: "lunge",
    season: 2,
  },
];
